config/routes.rb
Intest::Application.routes.draw do
  resources :resguardos
  root :to => redirect('/resguardos')









end

app/models/resguardo.rb
class Resguardo < ActiveRecord::Base
	mount_uploader :imagen, ImagenUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resguardos_controller.rb
class ResguardosController < ApplicationController
  before_action :set_resguardo, only: [:show, :edit, :update, :destroy]

  # GET /resguardos
  # GET /resguardos.json
  def index
    @resguardos = Resguardo.all
  end

  # GET /resguardos/1
  # GET /resguardos/1.json
  def show
  end

  # GET /resguardos/new
  def new
    @resguardo = Resguardo.new
  end

  # GET /resguardos/1/edit
  def edit
  end

  # POST /resguardos
  # POST /resguardos.json
  def create
    @resguardo = Resguardo.new(resguardo_params)

    respond_to do |format|
      if @resguardo.save
        format.html { redirect_to @resguardo, notice: 'Resguardo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @resguardo }
      else
        format.html { render action: 'new' }
        format.json { render json: @resguardo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resguardos/1
  # PATCH/PUT /resguardos/1.json
  def update
    respond_to do |format|
      if @resguardo.update(resguardo_params)
        format.html { redirect_to @resguardo, notice: 'Resguardo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resguardo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resguardos/1
  # DELETE /resguardos/1.json
  def destroy
    @resguardo.destroy
    respond_to do |format|
      format.html { redirect_to resguardos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resguardo
      @resguardo = Resguardo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resguardo_params
      params.require(:resguardo).permit(:no_resguardo, :concepto, :descripcion, :marca, :modelo, :imagen, :no_serie, :precio, :valor_actual, :ubicacion, :estado, :f_compra, :conectividad, :peso, :proveedor, :notas, :garantia)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resguardos_helper.rb
module ResguardosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Inventario Tijuana Propone</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Inicio</a></li>
        <li><a href="#">Configuración</a></li>
        
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Busqueda">
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Prestamos &nbsp<span class="badge">2</span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Bienvenido, David <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Perfil</a></li>
            <li><a href="#">Configuracion</a></li>
            <li><a href="#">Eliminar</a></li>
            <li class="divider"></li>
            <li><a href="#">Cerrar Sesion</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="row">
  <div class="col-md-1">
  	
  </div>
  <div class="col-md-10"><%= yield %></div>
  <div class="col-md-1"></div>
</div>
</div>

  

</body>
</html>

app/views/resguardos/_form.html.erb
<%= form_for @resguardo, :html => {:multipart => true} do |f| %>
  <% if @resguardo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resguardo.errors.count, "error") %> prohibited this resguardo from being saved:</h2>

      <ul>
      <% @resguardo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :no_resguardo %><br>
    <%= f.text_field :no_resguardo %>
  </div>
  <div class="field">
    <%= f.label :concepto %><br>
    <%= f.text_field :concepto %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br>
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br>
    <%= f.file_field :imagen %>
  </div>
  <div class="field">
    <%= f.label :no_serie %><br>
    <%= f.text_field :no_serie %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio %>
  </div>
  <div class="field">
    <%= f.label :valor_actual %><br>
    <%= f.text_field :valor_actual %>
  </div>
  <div class="field">
    <%= f.label :ubicacion %><br>
    <%= f.text_field :ubicacion %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :f_compra %><br>
    <%= f.date_select :f_compra %>
  </div>
  <div class="field">
    <%= f.label :conectividad %><br>
    <%= f.text_field :conectividad %>
  </div>
  <div class="field">
    <%= f.label :peso %><br>
    <%= f.text_field :peso %>
  </div>
  <div class="field">
    <%= f.label :proveedor %><br>
    <%= f.text_field :proveedor %>
  </div>
  <div class="field">
    <%= f.label :notas %><br>
    <%= f.text_field :notas %>
  </div>
  <div class="field">
    <%= f.label :garantia %><br>
    <%= f.text_field :garantia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resguardos/edit.html.erb
<h1>Editar Resguardo</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @resguardo %> |
<%= link_to 'Atras', resguardos_path %>

app/views/resguardos/index.html.erb
<h1>Listando resguardos</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>No. Resguardo</th>
      <th>Concepto</th>
      <th>Marca</th>
      <th>No. Serie</th>
      <th>Ubicacion</th>
      <th>Estado</th>
      <th>Notas</th>
      <th>Prestado a</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resguardos.each do |resguardo| %>
      <tr>
        <td><%= resguardo.no_resguardo %></td>
        <td><%= resguardo.concepto %></td>
        <td><%= resguardo.marca %></td>
        <td><%= resguardo.no_serie %></td>
        <td><%= resguardo.ubicacion %></td>
        <td><%= resguardo.estado %></td>
        <td><%= resguardo.notas %></td>
        <td><%= resguardo.proveedor %></td>
        <td><%= link_to 'Mostrar', resguardo, :class => "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_resguardo_path(resguardo), :class => "btn btn-info" %></td>
        <td><%= link_to 'Eliminar', resguardo, method: :delete, data: { confirm: 'Estas seguro?' } ,:class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear Resguardo', new_resguardo_path , :class => "btn btn-primary btn-lg" %>

app/views/resguardos/new.html.erb
<h1>Nuevo Resguardo</h1>

<%= render 'form' %>

<%= link_to 'Regresar', resguardos_path %>

app/views/resguardos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No resguardo:</strong>
  <%= @resguardo.no_resguardo %>
</p>

<p>
  <strong>Concepto:</strong>
  <%= @resguardo.concepto %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @resguardo.descripcion %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @resguardo.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @resguardo.modelo %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= image_tag(@resguardo.imagen_url) if @resguardo.imagen.present? %>
</p>

<p>
  <strong>No serie:</strong>
  <%= @resguardo.no_serie %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @resguardo.precio %>
</p>

<p>
  <strong>Valor actual:</strong>
  <%= @resguardo.valor_actual %>
</p>

<p>
  <strong>Ubicacion:</strong>
  <%= @resguardo.ubicacion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @resguardo.estado %>
</p>

<p>
  <strong>F compra:</strong>
  <%= @resguardo.f_compra %>
</p>

<p>
  <strong>Conectividad:</strong>
  <%= @resguardo.conectividad %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @resguardo.peso %>
</p>

<p>
  <strong>Prestado a:</strong>
  <%= @resguardo.proveedor %>
</p>

<p>
  <strong>Notas:</strong>
  <%= @resguardo.notas %>
</p>

<p>
  <strong>Garantia:</strong>
  <%= @resguardo.garantia %>
</p>

<%= link_to 'Editar', edit_resguardo_path(@resguardo) %> |
<%= link_to 'Regresar', resguardos_path %>